### ISSUE TITLE
변경된 견적서 모아보기 API 적용

### ISSUE THREAD

**Issue by blackhblee** [Step3-kakao-tech-campus/Team5_FE#102]
## Description

변경된 견적서 모아보기 API 적용

## To-do

- [x] 견적서 모아보기 mock api 수정
- [x] useFetchQuotationCollect 커스텀훅 수정
- [x] 견적서 모아보기 템플릿 수정
- [x] 진행 중인 견적서가 있을 때 표시되는 배너 수정
