### ISSUE TITLE
회원가입 페이지 보완

### ISSUE THREAD

**Issue by blackhblee** [Step3-kakao-tech-campus/Team5_FE#22]
## Description

회원가입 페이지 사용자 경험 향상

## To-do

- [x] API 호출 방식 변경
- [x] 회원가입 요청 중 스피너 구현
- [x] 리다이렉트 페이지 변경
