### ISSUE TITLE
폴더 구조 리팩토링

### ISSUE THREAD

**Issue by kimchanho97** [Step3-kakao-tech-campus/Team5_FE#24]
## Description

피드백 받은 내용을 토대로 수정

## To-do

- [x] 폴더 구조 변경
- [x] Modal -> BottomSheet 로 변경
- [x] 로그인 / 회원가입 페이지 헤딩 추가
