### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by blackhblee** [Step3-kakao-tech-campus/Team5_FE#3]
## Description

순수웨딩 프로젝트 초기 설정

## To-do

- [x] 프로젝트 생성 및 라이브러리 추가
- [x] 디렉터리 설정
- [x] 커스텀 색상 추가
- [x] README.md 수정
