### ISSUE TITLE
GNB sticky & BottomSheet, 마이페이지 디자인 변경

### ISSUE THREAD

**Issue by blackhblee** [Step3-kakao-tech-campus/Team5_FE#40]
## Description

GNB sticky & BottomSheet, 마이페이지 디자인 변경

## To-do

- [x] GNB sticky 적용 후에도 레이아웃 버그가 없도록 수정
- [x] BottomSheet 디자인 변경
- [x] 마이페이지 디자인 변경
