### ISSUE TITLE
포트폴리오 페이지 구현

### ISSUE THREAD

**Issue by blackhblee** [Step3-kakao-tech-campus/Team5_FE#44]
## Description

포트폴리오 페이지 구현

## To-do

- [x] 포트폴리오 페이지 구현 (캐러셀 제외)
- [x] 스피너 구현
- [x] mock 데이터 수정
- [x] 포트폴리오 페이지에서 GNB 아이콘 활성화가 되도록 수정
