### ISSUE TITLE
API Mocking & 초기설정

### ISSUE THREAD

**Issue by kimchanho97** [Step3-kakao-tech-campus/Team5_FE#5]
## Description
API 명세서를 바탕으로 Mocking하여 request에 따른 response와 error를 구현

## To-do

- [x] 기본적인 api 구현
- [x] Mock up Data 생성
- [x] Mocking Handler 구현
- [x] MainLayout 생성
