### ISSUE TITLE
디자인 수정

### ISSUE THREAD

**Issue by blackhblee** [Step3-kakao-tech-campus/Team5_FE#61]
## Description

디테일한 디자인 수정

## To-do

- [x] 헤더 추가
- [x] 캐러셀 디자인 수정
- [x] 포트폴리오 페이지 가독성 향상 및 버튼 디자인 수정
- [x] 전체적인 여백 수정
