### ISSUE TITLE
글로벌 바텀시트 렌더링 및 상태관리

### ISSUE THREAD

**Issue by kimchanho97** [Step3-kakao-tech-campus/Team5_FE#67]
## Description

로그인 요청 바텀시트 또는 서버에러 바텀시트 등 전역으로 여러 곳에서 사용되는 컴포넌트의 상태를 최상위에서 관리하고 렌더링

## To-do

- [x] 글로벌 바텀시트 컴포넌트 생성
- [x] 상태 변경 액션 정의
- [x] open, close 함수 정의
