### ISSUE TITLE
검색 기능 구현

### ISSUE THREAD

**Issue by kimchanho97** [Step3-kakao-tech-campus/Team5_FE#69]
## Description

포트폴리오를 플래너의 이름으로 검색하는 기능 구현

## To-do

- [x] SearchBar 컴포넌트 생성
- [x] 메인페이지에서 쿼리파라미터 관리
- [x] 검색 페이지에서 쿼리파라미터 변경시 api 요청
