### ISSUE TITLE
디자인 수정

### ISSUE THREAD

**Issue by blackhblee** [Step3-kakao-tech-campus/Team5_FE#72]
## Description

디테일한 디자인 수정

## To-do

- [ ] 커스텀 아이콘 추가 및 적용
- [ ] 일부 컴포넌트에 커스텀 스피너 적용
- [ ] 일부 컴포넌트 여백 수정
- [ ] 아래와 같이 채팅 메시지 border-radius 수정
<img width="837" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team5_FE/assets/53530683/4cddf949-65b0-495a-a079-412e5853bc62">
